### ISSUE TITLE
Filters not applied when sending the campaign

### ISSUE THREAD

**Issue by loremuttoni** [bramley/phplist-plugin-segment#10]
```
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
PHPlist 3.3.1
Common Plugin: version 3.5.16+20170402
Segmentation: version 2.2.1+20170208
```

Everything is correctly installed.
I can set attributes and values in the "segment tab" and, if I press "Calculate", the number of recipients is what I'm expecting.
However, when I process the queue, the number of subscribers is the original one, as I didn't apply the filters.
What can I do? Is there any further configuration I'm missing? 
Thanks in advance.

**Comment by bramley** [comment]
What do you mean by "the number of subscribers is the original one"? 

phplist will actually process all subscribers who are on the list, regardless of segment conditions, but the plugin will reject sending to those who do not meet the conditions. So the total processed will be all subscribers, but the total sent will be less.
![image](https://cloud.githubusercontent.com/assets/3147688/24649898/769ce562-1920-11e7-940f-1d71bf27a293.png)

**Comment by loremuttoni** [comment]
Good morning,

thank you for the quick answer.

I'll show you some numbers so that it's more clear:

/Number of subscribers without filters/: *31386* ("Calculate button"
with no filter selected)
/Number of subscribers after applying the filters/: *11060* ("Calculate
button" with filters)

When I launch "phplist.sh -pprocessqueue", I get:

*phpList version 3.3.1 (c) 2000-2017 phpList Ltd, http://www.phplist.com**
**phpList - Started [0.0444580000] (105)**
**phpList - Processing has started, [0.0014320000] (108)**
**phpList - One campaign to process. [0.0066530000] (110)**
**phpList - Processing message 24 [0.3650660000] (131)**
**phpList - Looking for subscribers [0.0107440000] (136)**
**phpList - Found them: 31386 to process [0.2410650000] (142)*


Where am I wrong?

Thanks for your attention.
Lorenzo

**Comment by bramley** [comment]
That is exactly what I explained. In my example there were 176 subscribers on the list but only 37 were selected by the plugin and sent an email.

If you are not sure about whether the plugin will select the correct subscribers then I recommend that you use a test list with a small number of subscribers. Then it will be easier to see what is happening.

**Comment by loremuttoni** [comment]
Thank you very much. You've removed all my doubts.
