### ISSUE TITLE
Segment plugin not working

### ISSUE THREAD

**Issue by shivshankardayal** [bramley/phplist-plugin-segment#11]
PHPList version: 3.3.1
Common Plugin Version: 3.6.4+20170625
Segment Plugin Version: 2.2.1+20170208

It queues the entire list and not the segment it is asked for.

**Comment by bramley** [comment]
What do you mean by "queues the entire list"? You will need to provide a more detailed explanation of what you are doing and why you think the result is wrong.

**Comment by shivshankardayal** [comment]
A CSV is uploaded as a list with a code attribute for segmentation. I choose a code (a number) on SEGMENT tab which is the attribute. My list size is 200k and segment size is 20k. But campaigns are listed for 200k instead for 20k.

**Comment by bramley** [comment]
That is the way the plugin works. I have updated the documentation to explain that, see https://resources.phplist.com/plugin/segment?&#purpose but I recommend that you send a test campaign to a small list to ensure that you can see that the correct subscribers are selected.

**Comment by shivshankardayal** [comment]
The plugin is working. However, the message showed on site is wrong. It lists the number of subscribers for the entire list. Mails are sent only for the no. of subscribers in the segment.

Closing the issue.
