### ISSUE TITLE
Extend message displayed when no Lists are selected

### ISSUE THREAD

**Issue by samtuke** [bramley/phplist-plugin-segment#13]
Commit 6eda522f9aab206605c34c1641d6f6f0059c548e added a warning for the user when no Lists have been selected for the campaign being edited on the Segment tab. The warning text states 'No lists have been selected on the Lists tab'. This may not sufficiently clear for some users. Proposed extension:

'No lists have been selected on the Lists tab - please select at least one list before adding segmentation conditions'

The purpose is to ensure the user understands that action should be taken.

**Comment by bramley** [comment]
The need to have chosen some lists is for the Calculate button to produce something other than "0 subscribers". You can enter the conditions without having selected a list, but even then you won't be able to submit the campaign on the Finish tab. I will think about rewording the warning message.
