### ISSUE TITLE
UI improvement ideas

### ISSUE THREAD

**Issue by samtuke** [bramley/phplist-plugin-segment#14]
After spending some time using this plugin and brainstorming with @suelap, I'd like to share the following ideas for improving the user interface of this plugin.

A mockup screenshot made with Firefox demonstrates the changes combined (please ignore whitespace issues):

![selection_349](https://user-images.githubusercontent.com/695422/33679552-597f9f68-dabf-11e7-90b8-91593fc8e170.png)

**Ideas**:

1. Add the following placeholder text for the field 'Save the current segment (set of conditions).': 'name of segment'
1. Add the following placeholder text for the field 'Use one or more pre-save segments.': 'names of saved segments'
1. If no saved segments exist, then grey out the associated buttons using .deactivated class (bootstrap)
1. Change 'Load' button text to 'Load segments'
1. Move 'Use one or more saved segments' field group above the other sections (most often if the user wants to load a saved segment then this will be the first step in their workflow)
1. Add an HR element after the introductory paragraph at the top of the page, and consider making it bold (it needs to stand out and is more important than any text below as it explains the use of the tab)
1. Add missing spaces between sentences in the opening paragraph text
1. Rephrase "choose 'Select ..." from the drop-down list' to be less ambiguous (using 'Select...' is both how you start creating, and also how you unset a condition)
1. Add help text/icon to settings page 'Summary of saved segments', explaining what it does (when the field is empty, it's not clear what to expect there)
1. Left align fields underneath: 'Subscribers match of the following:' for consistency
1. Make 'Edit saved segments' link into a button named 'Edit segments', next to 'Save segment', and move it next to 'Load segment' (most often users will be prompted to edit or delete saved segments immediately after viewing the list of available segments and/or loading some)
1. Make 'guidance on usage' into a contextual help button on top right of overall tab panel

@bramley What do you think?

**Comment by bramley** [comment]
I'm not sure that you are using the current version of the plugin, 2.2.4+20171109. Please confirm whether that is the case. Some of these comments do not appear to be accurate now.

**Comment by bramley** [comment]
1 and 2 - The suggested placeholder texts might have the effect of widening the fields unnecessarily. I would need to try it out.
3 - when there are no saved segments then the related fields are not displayed. This was changed on October 23 https://github.com/bramley/phplist-plugin-segment/blob/master/changelog.txt
4 - I think the suggested text might make the button unnecessarily wide but would need to try it out.
5 - this separates the explanatory text from the fields that is it describing
6 - I can try this change to see how it looks. More preferable than simply making bold is to use a style already defined for explanatory text, if there is one.
7 - This was changed a while ago.
8 - I don't understand this point.
9 - this would be a change to core phplist
10 - I think the fields are already aligned, or as close that I can make them.
11 - It is already a button
12 - I'm not entirely sure where you mean, but this is likely a change to core phplist.

**Comment by bramley** [comment]
I have made some of the layout and wording changes and put the usage information into a "note" div so that it stands-out.

![image](https://user-images.githubusercontent.com/3147688/34105513-74deceba-e3ec-11e7-8dc4-476a77479180.png)

**Comment by samtuke** [comment]
The changes look very good, thank you. We will test them and report back.
