### ISSUE TITLE
Field limitation

### ISSUE THREAD

**Issue by lcassisi** [bramley/phplist-plugin-segment#18]
On file /phplist/admin/plugins/common/DAO/Attribute.php, line 28 there's a line limiting to 15 the number of fields to show, which does the work in an arbitrary way. I think this behavior can be modified extending Common\DAO class.
This is the function where the problem is:

public function __construct($dbCommand, $attrNameLength = 20, $maxAttrs = 15)
    {
        $this->attrNameLength = $attrNameLength;
        $this->maxAttrs = $maxAttrs;
        parent::__construct($dbCommand);
    }

**Comment by bramley** [comment]
Thanks for highlighting the problem for the Segment plugin. That is an inadvertent effect of a recent change I made. Prior to that change `$maxAttrs` was passed a value of 0 meaning there was not a limit on the number of attributes. I will look at fixing the problem for the Segment plugin.

The original reason for the limit on attribute name length and number of attributes was for the Subscribers plugin which displays all attribute names, but that looked bad when there were loads of attributes or with long names.

**Comment by bramley** [comment]
The problem is now fixed. You can install the new version on the Manage Plugins page  using this package url `https://github.com/bramley/phplist-plugin-segment/archive/master.zip`

**Comment by lcassisi** [comment]
Thank you very much!
