### ISSUE TITLE
I would like to translate.

### ISSUE THREAD

**Issue by actXc** [bramley/phplist-plugin-segment#2]
Dear Duncan,
thank you for publihsing the code.
I would like to translate the user interface into German.
How to start?
would we add this to pootle?

**Comment by bramley** [comment]
This is probably an issue for phplist itself, rather than the plugin. I raised it on the developers mailing list http://sourceforge.net/p/phplist/mailman/message/32922971/ but didn't get a clear response. I suggest you raise the issue again on either the developers or translators mailing lists.
