### ISSUE TITLE
Date range Not working

### ISSUE THREAD

**Issue by etreby** [bramley/phplist-plugin-segment#4]
when i try to set date range it is not working

**Comment by bramley** [comment]
You will need to provide more information on exactly what is not working.
Is it a date attribute or the subscriber entered date that you are using? And what is the date range you entered and the subscriber date value that is not being selected?

**Comment by etreby** [comment]
choosing from the segment tap on campaign user attribute date and select matcher as between and put date range from 1 April 2015 to 30 April 2015 on this attribute and click calculate it gives me 0 but i am sure that i out user attrebuits on this list matching this i found out the problem with file DateConditionBase.php class SegmentPlugin_DateConditionBase::validateDates function which take the operator and dates as array $target1 and to i replaced the new DateTime class to convert to date('Y-m-d',strtotime($value[0])); and it's working now which is weird

**Comment by bramley** [comment]
Thanks for the explanation but I cannot repeat the problem. I get the same result using a DateTime object as your workaround with strtotime.
What is your php version, and which timezone are you in?
And what is the actual value of the date attribute that is now included?
