### ISSUE TITLE
Message can't be edited when attribute used in selction has been deleted

### ISSUE THREAD

**Issue by MarcelvC** [bramley/phplist-plugin-segment#6]
While testing the changes I made to the plugin, I noticed that trying to open a draft message throws an error, when an attribute was previously used in selection that has subsequently been deleted from the system. The message can't be edited or opened.

Maybe a possible solution would be to automatically delete the corresponding database entry from the "messagedata" table for the selection when a message containing a selection with a deleted attribute is opened?

----

Here's the error message (edited):

Notice: Undefined offset: 11 in /admin/plugins/SegmentPlugin/ConditionFactory.php on line 42

Fatal error: Uncaught exception 'Exception' with message 'unrecognised type ' in /admin/plugins/SegmentPlugin/ConditionFactory.php:64

Stack trace:
#0 admin/plugins/SegmentPlugin.php(215): SegmentPlugin_ConditionFactory->createCondition('11')

#1 /admin/send_core.php(586): SegmentPlugin->sendMessageTab('418', Array)

#2 /admin/send.php(115): include('/www/htdocs/w00...')

#3 /admin/index.php(517): include('/www/htdocs/w00...')

#4 {main} thrown in /admin/plugins/SegmentPlugin/ConditionFactory.php on line 64

phpList version 3.0.12

**Comment by bramley** [comment]
This is a good point. To workaround the problem you will need to delete manually the row from the messagedata table. I will issue a new release shortly.

**Comment by MarcelvC** [comment]
Yes, that's in fact exactly what I did and why I thought of this solution. :-)
