### ISSUE TITLE
FR: Segmentation Search and List Add via Cron Job

### ISSUE THREAD

**Issue by justinputney** [bramley/phplist-plugin-segment#7]
These are some great plugins!

I'm wondering if there is a way to use segmentation or the subscriber plugin to grab a certain list of subscribers and add them to another list.

I'd like to be able to automate this from a cron job. Essentially, I'm looking for a way to move people to my main list after they've completed mini courses via the Autoresponder plugin.

It would work like this: Someone signs up for an Autoresponder list and gets a series of emails, when they reach the end Autoresponder list, I want to move/copy them to my main list.

The segmentation is a good way to send emails to this group (but looking checking to see if they have the last Autoresponder attribute set to NOT NULL), but it would be even better if I could copy them to my main list and track everyone from there. Ideally, this would be part of the Autoresponder plugin, but I'll take it wherever I can make it work.

Thanks for creating all of this awesome functionality!

**Comment by bramley** [comment]
Functionality added to the Autoresponder plugin.
