### ISSUE TITLE
Error message displayed when viewing a sent campaign with deleted attribute in segmentation

### ISSUE THREAD

**Issue by MarcelvC** [bramley/phplist-plugin-segment#9]
When viewing a sent campaign in which an attribute was used in segmentation that has since been deleted error messages are displayed at the top of the page and under "segment conditions". The functionality of phpList doesn't seem to be affected.

Maybe it would be possible to save the segment of each campaign as text so that it can be displayed in the event that one of the attributes (or attribute values) has been deleted? For "historic" campaigns (i.e. those that have already been sent) or as an alternative to the first suggestion maybe a boilerplate note could be displayed under "segment conditions" that the segment can't be displayed since one of the attributes has been deleted?

phpList version 3.2.4
Plugin version 2.1.4+20151117

**Comment by bramley** [comment]
> error messages are displayed at the top of the page and under "segment conditions".

In order to ensure that I am looking at the same problem, please can you include screenshots of the errors that you are seeing?

**Comment by MarcelvC** [comment]
Of course! Sorry that I hadn't included them before! I didn't because I was using my own modified version of the plugin so the line numbers would have been wrong but I have now temporarily installed your original version of the plugin for the screenshots.

![screenshot-www jef-hessen de 2016-03-15 10-26-05](https://cloud.githubusercontent.com/assets/12641226/13773336/043e1df8-ea99-11e5-88ce-ebb1e3ae1442.png)

![screenshot-www jef-hessen de 2016-03-15 10-29-15](https://cloud.githubusercontent.com/assets/12641226/13773337/043fb92e-ea99-11e5-8b88-c05d02ab01c3.png)

**Comment by bramley** [comment]
I have made some changes to handle the case when an attribute no longer exists. 
Can you try this branch https://github.com/bramley/phplist-plugin-segment/archive/issue_9.zip to see whether it resolves your problem, it should do.

You can install that on the Manage Plugins page using the url for the zip file, but beware that will overwrite the version that you currently have installed.

**Comment by MarcelvC** [comment]
It does indeed resolve the problem, thanks a lot! Great!
